import Head from 'next/head'
import Image from 'next/image'
// import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Idealake Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Link href="/about">
          <a>About Us</a>
        </Link>
        <Link href="/contact">
          <a>contact</a>
        </Link>
      </main>

     
    </div>
  )
}
